### PR TITLE
Add mruby-mutex

### PR DESCRIPTION
**Pull request by matsumoto-r**

### CODE REVIEW

**Comment by mattn** [comment]
Why new2? https://github.com/matsumoto-r/mruby-mutex

**Comment by mattn** [comment]
FYI mruby-thread has implementation of Mutex/Queue https://github.com/mattn/mruby-thread :)

**Comment by matsumoto-r** [comment]
> FYI mruby-thread has implementation of Mutex/Queue https://github.com/mattn/mruby-thread :)

Thank you for your information! mruby-mutex have global mutex between processes.

> Why new2? https://github.com/matsumoto-r/mruby-mutex/blob/master/src/mrb_mutex.c#L122

I don't like parse args in C. So I wrapped `new2` method by `new` in mrblib/mrb_mutex.rb.

**Comment by mattn** [comment]
> I don't like parse args in C. So I wrapped new2 method by new in mrblib/mrb_mutex.rb.

Ah, I miss it. Thank you

**Pull request merged**
