### PR TITLE
Add mruby-factory

### PR DESCRIPTION
**Pull request by okuramasafumi**

### CODE REVIEW

**Comment by dearblue** [comment]
@okuramasafumi,
The default branch is "master" if `branch` is not specified in the "*.gem" file.
I recommend adding a "master" branch to your repository or adding `branch: main` to your "mruby-factory.gem" file.

**Comment by okuramasafumi** [comment]
@dearblue Thanks, I'll update it with another PR.
I also noticed that it's not mentioned in the example section in README. Should I add `branch` to that example as well?

**Comment by dearblue** [comment]
Indeed, at the moment, it seems to be a hidden feature that does not exist in `mgem-list/README.md` nor in `mruby/doc`.
Yes, it would be better if a description was added.

**Comment by matz** [comment]
I renamed it to add `.gem` suffix. (d5e106c099095d738ccd429bf6241a799a96780f) If you need to specify the branch name, send us PR.

**Comment by okuramasafumi** [comment]
@matz Sorry for confusion, now I got where the default branch is set.
https://github.com/mruby/mruby/blob/master/lib/mruby/build/load_gems.rb#L254
Here the branch option falls back to `@branch`, and:
https://github.com/mruby/mruby/blob/master/lib/mruby/build/load_gems.rb#L100
Here the default value for `@branch` is `master`.

I'll create two Pull Requests. One is to fix default branch for `mruby-factory` and another is to mention default branch in the doc.

**Pull request merged**
