### PR TITLE
Add mruby-qrcode

### PR DESCRIPTION
**Pull request by scalone**

### CODE REVIEW

**Comment by matz** [comment]
Can you specify the license in the `mruby-qrcode.gem` file?

**Comment by scalone** [comment]
Hey @matz sorry, you mean like this, in `mruby-qrcode.gem`:
```
+license: MIT
+name: mruby-qrcode
+description: Ruby interface to QR Code C Library by Ryusuke SEKIYAMA
+author: ['sadasant', 'scalone']
+website: https://github.com/scalone/mruby-qrcode
+protocol: git
+repository: https://github.com/scalone/mruby-qrcode.git
```
or in `mrbgem.rake`(https://github.com/scalone/mruby-qrcode/blob/master/mrbgem.rake#L2)?

**Comment by matz** [comment]
I meant `mruby-qrcode.gem` file.

**Comment by matz** [comment]
Thank you. `mgem-list` became better with your effort.

**Pull request merged**
