### PR TITLE
Add 3 gems that I have created

### PR DESCRIPTION
**Pull request by udzura**
Hi, details are on the added files.

Thank you!

### CODE REVIEW

**Comment by matz** [comment]
I think some of those gem names are too generic. Could you rename them, for example, mruby-namespace to mruby-linux-namespace?

**Comment by udzura** [comment]
It's ok to rename, but I'm now using mruby-namespace so it may take some minutes to modify.

Is there any mgems to be renamed?

**Comment by matz** [comment]
I have impression that mruby-exec and mruby-mount are too generic too. I have no particular renaming idea yet though. Perhaps mruby-syscall-exec and mruby-syscall-mount, or mruby-process-exec and mruby-fs-mount?

**Comment by udzura** [comment]
I understand.

In fact, I think both `mruby-exec` and `mruby-mount` are not "mature" mgems enough and have little features, so they cannot be named properly yet.
How about removing these two at this time?

**Comment by matz** [comment]
It's totally up to you. Sorry for bothering.

**Comment by bovi** [comment]
@udzura what about something like "mruby-sys-*". I had a look at your mgems and I personally find them quite useful. I wonder if it would make sense if mount and exec would maybe be handled under a single module (e.g. Sys:: or System::). Then all the users of your mgems could tune their system module as they like by adding the features they need for the environment they have.

**Comment by udzura** [comment]
@bovi 

Thanks! I'm going to consider gem names and each gem's domain to control system calls/OS features.
`mruby-sys-*` series (or yet another prefix) look a good solution.

At this time I will rename to mruby-linux-namespace and temporary remove mruby-exec/mount

@matz @bovi Thanks for your advice!!

**Pull request merged**
