### PR TITLE
Add mruby-strptime

### PR DESCRIPTION
**Pull request by naritta**
I added mruby-strptime.
https://github.com/naritta/mruby-strptime

### CODE REVIEW

**Comment by matz** [comment]
Could you specify the license for the gem? (I know it's MIT)

**Comment by naritta** [comment]
I see, I added the license here.
https://github.com/naritta/mruby-strptime/commit/af81ce34ea89740491f7f45fecc92df34a909054

**Comment by matz** [comment]
Thank you.

**Comment by naritta** [comment]
Thank you for reviewing.

**Pull request merged**
