### PR TITLE
Create mruby-hiredis.gem

### PR DESCRIPTION
**Pull request by Asmod4n**

### CODE REVIEW

**Comment by zzak** [comment]
@Asmod4n Have you tried [mruby-redis](https://github.com/matsumoto-r/mruby-redis)?

**Comment by Asmod4n** [comment]
@zzak yes, but it was lacking pipelines and transactions. Also every redis command was written as its own c method. Changing that would have required substantial changes to it.

**Comment by Asmod4n** [comment]
@zzak i usually don't go that route, like: "thanks for all your effort, ill remove 75% of it"

**Comment by zzak** [comment]
@Asmod4n Ok! I was just curious the differences, and if we could work together somehow.

It seems like there are 2 different design goals, and that's fine! :)

Thanks for your contributions to the mruby community <3

**Comment by Asmod4n** [comment]
Thank you! I totally love mruby :)

**Comment by Asmod4n** [comment]
@zzak i believe we can at least bring pipelining over: https://github.com/matsumoto-r/mruby-redis/issues/46

**Pull request merged**
