### PR TITLE
Add mruby-sidekiq-client.gem

### PR DESCRIPTION
**Pull request by monochromegane**

### CODE REVIEW

**Comment by monochromegane** [comment]
Thaks!

**Comment by matsumoto-r** [comment]
You can link mruby-sidekiq-client into mruby by writing the following configuration in build_config.rb:

```ruby
conf.gem :mgem => 'mruby-sidekiq-client'
```

Thanks!

**Comment by monochromegane** [comment]
It's useful :+1:

**Comment by udzura** [comment]
:tada:

**Pull request merged**
