### PR TITLE
Add mruby-gemcut

### PR DESCRIPTION
**Pull request by dearblue**

### CODE REVIEW

**Comment by matz** [comment]
I wish `mruby-gemcut` had English `README`. Google translation is OK for the starting point.

**Comment by dearblue** [comment]
Changed README to English.

**Comment by matz** [comment]
Thank you. It is pity to restrict users to Japanese speaking people. (もったいない)

**Comment by dearblue** [comment]
I planned to include an English README when mruby-gemcut-1.0 was released.
By the way, mruby-gemcut-1.0 will be released in 255 years.

Thank you for your response.

**Pull request merged**
