### PR TITLE
Added file to mention my Mruby marshalling code

### PR DESCRIPTION
**Pull request by asfluido**
As requested, here is my pull request for adding the record mentioning the marshalling code I wrote in `mgem-list`. Thanks!

### CODE REVIEW

**Comment by bovi** [comment]
@asfluido could you add a license property to the file? e.g. like here: https://github.com/mruby/mgem-list/blob/master/mruby-ansi-colors.gem

**Comment by asfluido** [comment]
Uh... I copied the file from the original marshalling contribution, which did not have that line.
Which license is the main mruby codebase released as?

**Comment by asfluido** [comment]
Actually, that's different. It looks like I forked an older version of the repository... Don't know how. Anyway, I added the line now.

**Comment by bovi** [comment]
thanks @asfluido and sorry for the license confusion. we added that as a requirment some time ago so that people who are using the GEMa get an easy overview what licenses are combined into their mruby build.

**Comment by asfluido** [comment]
Thank you!  And have a nice day

**Pull request merged**
