### PR TITLE
Create mruby-wslay.gem

### PR DESCRIPTION
**Pull request by Asmod4n**

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Could you write README? #120 #121 #127

**Comment by Asmod4n** [comment]
@matsumoto-r its a bit tricky for wslay, you need most of these gems to write a small README: https://github.com/Asmod4n/mruby-websockets/blob/master/mrbgem.rake

**Comment by Asmod4n** [comment]
@matsumoto-r updated the README.

**Comment by matsumoto-r** [comment]
:+1:

**Pull request merged**
